apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatap-open-agent-sa
  namespace: whatap-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whatap-open-agent-role
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "endpoints", "namespaces"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: [ "/metrics" ]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: whatap-open-agent-role-binding
subjects:
- kind: ServiceAccount
  name: whatap-open-agent-sa
  namespace: whatap-monitoring
roleRef:
  kind: ClusterRole
  name: whatap-open-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatap-open-agent
  namespace: whatap-monitoring
  labels:
    app: whatap-open-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatap-open-agent
  template:
    metadata:
      labels:
        app: whatap-open-agent
    spec:
      serviceAccountName: whatap-open-agent-sa
      containers:
      - name: whatap-open-agent
        image: whatap/open_agent:arm64-test
        imagePullPolicy: Always
        env:
        - name: WHATAP_LICENSE
          valueFrom:
            secretKeyRef:
              name: whatap-credentials
              key: license
        - name: WHATAP_HOST
          valueFrom:
            secretKeyRef:
              name: whatap-credentials
              key: host
        - name: WHATAP_PORT
          valueFrom:
            secretKeyRef:
              name: whatap-credentials
              key: port
        volumeMounts:
        - name: config-volume
          mountPath: /app/scrape_config.yaml
          subPath: scrape_config.yaml
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: config-volume
        configMap:
          name: whatap-open-agent-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatap-open-agent-config
  namespace: whatap-monitoring
data:
  scrape_config.yaml: |
    # New CR format configuration
    features:
      openAgent:
        enabled: true
        # Global default settings (can be overridden in targets)
        globalInterval: "30s"
        globalPath: "/metrics"
        targets:
          # Example ServiceMonitor for kube-apiserver
          - targetName: dcgm-exporter
            type: PodMonitor
            namespaceSelector:
              matchNames:
                - "whatap-monitoring"
            selector:
              matchLabels:
                name: whatap-node-agent
            endpoints:
              - port: "http"
                path: "/metrics"
                interval: "30s"
                scheme: "http"
                tlsConfig:
                  insecureSkipVerify: true
            metricRelabelConfigs:
              - target_label: wtp_src
                replacement: "true"
                action: replace
          - targetName: kube-apiserver
            type: ServiceMonitor
            namespaceSelector:
              matchNames:
                - "default"
            selector:
              matchLabels:
                component: apiserver
                provider: kubernetes
            endpoints:
              - port: "https"
                path: "/metrics"
                interval: "30s"
                scheme: "https"
                tlsConfig:
                  insecureSkipVerify: true
            metricRelabelConfigs:
              - source_labels: [__name__]
                regex: "apiserver_request_total"
                action: keep
              - source_labels: [verb]
                target_label: http_verb
                replacement: "${1}"
                action: replace
              - target_label: wtp_src
                replacement: "true"
                action: replace
